- uses: actions/setup-python@v6
  with:
    python-version: "3.12"
- if: runner.os != 'Windows'
  shell: bash
  run: echo "PYO3_PYTHON=python3" >> $GITHUB_ENV
- if: runner.os == 'Windows'
  shell: pwsh
  run: echo "PYO3_PYTHON=python" >> $GITHUB_ENV
