//! Parse plugin JSON into Plugin manifest structs
//!
//! Converts JSON generated by ast-grep discovery into
//! Plugin manifest structures.

use crate::plugin_manifest::{CallableMetadata, ConfigMetadata, Plugin, UpgraderMetadata};

/// Parse plugin JSON from ast-grep discovery into Plugin structs
pub fn parse_plugin_json(
    json: &str,
    package_name_full: &str,
) -> Result<Vec<(String, Plugin)>, String> {
    let package: serde_json::Value =
        serde_json::from_str(json).map_err(|e| format!("Failed to parse plugin JSON: {}", e))?;

    let mut plugins = Vec::new();

    if let Some(plugins_array) = package.get("plugins").and_then(|p| p.as_array()) {
        for plugin_obj in plugins_array {
            let plugin_name = plugin_obj
                .get("name")
                .and_then(|n| n.as_str())
                .ok_or_else(|| "Plugin missing 'name' field".to_string())?;

            let plugin_type = plugin_obj
                .get("plugin_type")
                .and_then(|t| t.as_str())
                .map(|s| s.to_string());

            let io_type = plugin_obj
                .get("io_type")
                .and_then(|t| t.as_str())
                .map(|s| s.to_string());

            let call_method = plugin_obj
                .get("call_method")
                .and_then(|m| m.as_str())
                .map(|s| s.to_string());

            let obj = plugin_obj.get("obj").cloned();
            let config = plugin_obj.get("config").cloned();
            let requires_store = plugin_obj.get("requires_store").and_then(|r| r.as_bool());

            // Extract upgrader-specific fields
            let upgrader = if plugin_obj.get("version_strategy").is_some()
                || plugin_obj.get("version_reader").is_some()
                || plugin_obj.get("upgrade_steps").is_some()
            {
                let version_strategy_json = plugin_obj
                    .get("version_strategy")
                    .map(|v| v.to_string());

                let version_reader_json = plugin_obj
                    .get("version_reader")
                    .map(|v| v.to_string());

                let upgrade_steps_json = plugin_obj
                    .get("upgrade_steps")
                    .map(|u| u.to_string());

                if version_strategy_json.is_some() || version_reader_json.is_some() || upgrade_steps_json.is_some() {
                    Some(UpgraderMetadata {
                        version_strategy_json,
                        version_reader_json,
                        upgrade_steps_json,
                    })
                } else {
                    None
                }
            } else {
                None
            };

            let plugin = Plugin {
                package_name: Some(package_name_full.to_string()),
                plugin_type,
                description: None,
                doc: None,
                io_type,
                call_method,
                requires_store,
                obj: obj.and_then(|o| {
                    if o.is_null() {
                        None
                    } else {
                        serde_json::from_value::<CallableMetadata>(o).ok()
                    }
                }),
                config: config.and_then(|c| {
                    if c.is_null() {
                        None
                    } else {
                        serde_json::from_value::<ConfigMetadata>(c).ok()
                    }
                }),
                upgrader,
                install_type: None,
                installed_by: None,
            };

            plugins.push((plugin_name.to_string(), plugin));
        }
    }

    Ok(plugins)
}
